# This is an example nextest configuration for this repository. See nextest-runner/default-config.toml
# for more information.
default-profile = "dijets-devtools"

[profiles.dijets-devtools]
name = "dijets-devtools-run"
retries = 0
failure-output = "immediate-final"
metadata-key = "dijets-devtools"

[metadata.dijets-devtools]
dir = "target/nextest"
junit = "junit.xml"
